apiVersion:  v1 
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: expense
spec: 
  storageClassName: "expense-ebs"
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi